// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.DataAccess;

namespace Project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190404214510_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project.Models.EF_Models+Company", b =>
                {
                    b.Property<string>("symbol")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.Property<string>("type");

                    b.Property<string>("website");

                    b.HasKey("symbol");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Project.Models.EF_Models+Financials", b =>
                {
                    b.Property<decimal>("cashFlow");

                    b.Property<decimal>("costOfRevenue");

                    b.Property<decimal>("currentAssets");

                    b.Property<decimal>("currentCash");

                    b.Property<decimal>("currentDebt");

                    b.Property<decimal>("grossProfit");

                    b.Property<decimal>("netIncome");

                    b.Property<string>("symbol");

                    b.Property<decimal>("totalAssets");

                    b.Property<decimal>("totalCash");

                    b.Property<decimal>("totalDebt");

                    b.Property<decimal>("totalLiabilities");

                    b.Property<decimal>("totalRevenue");

                    b.HasKey("cashFlow");

                    b.ToTable("Financials");
                });

            modelBuilder.Entity("Project.Models.EF_Models+KeyStats", b =>
                {
                    b.Property<string>("symbol")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("NamedividendRate");

                    b.Property<decimal>("cash");

                    b.Property<decimal>("debt");

                    b.Property<decimal>("grossProfit");

                    b.Property<decimal>("revenue");

                    b.Property<decimal>("revenuePerShare");

                    b.HasKey("symbol");

                    b.ToTable("KeyStats");
                });

            modelBuilder.Entity("Project.Models.EF_Models+Login", b =>
                {
                    b.Property<string>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("UserID");

                    b.ToTable("Login");
                });
#pragma warning restore 612, 618
        }
    }
}
